/*
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
     10: 1,2,5,10
     15: 1,3,5,15
     21: 1,3,7,21
     28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

#include <bits/stdc++.h>

#define META 500

int calcularNumeroTriangular(int n){ 
    return ((1 + n) * n)/2;
}

int numeroDivisores(int num) {
    int resultado = 0;
    for (int i = 1; i <= num; i++){
        if (num % i == 0) {
            resultado++;
        }
    }
    return resultado;
}

int main (){
    int i = 1;
    while (numeroDivisores(calcularNumeroTriangular(i)) < META){
        i++;
    }
    std::cout << i << "o número, " << calcularNumeroTriangular(i) << ", com " << numeroDivisores(calcularnumerotriangular(i)) << " divisores" ;
    return 0;
}

// Resultado:
// 12375o número, 76576500, com 576 divisores
// real	21m37,261s
// user	21m36,552s
// sys	0m0,233s
