/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
#include <iostream>
#define LIMIT 4000000

using namespace std;

int main(){
    long long x = 1;
    long long y = 0;
    long long even_sum = 0;

    for (long long sum = 1; sum <= LIMIT; sum += y){
        y = x;
        x = sum;
        if (sum % 2 == 0){
            even_sum += sum;
        }
    }
    cout << "[EVEN SUM] " << even_sum << "\n"; 
    return 0;
}
